name: Feature request
description: Propose a YieldOS capability
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: What problem does this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed approach (metadata-first)
    validations:
      required: true
